#!/usr/bin/env sh
# @(#) 05-VMw-sync-dq-cloud-fs
# VMware Sync-DQ-Cloud filesystem creation
# Last-edited: 2022.04.28.0126.Thu -- Danny Quah (me@DannyQuah.com)
# ****************************************************************
# Revision History:
#  % 2022.04.24.1746.Sun -- Danny Quah (me@DannyQuah.com)
# ****************************************************************
#
################################
# Assumes VMware Ubuntu, and that Internet-Cloud folders will
# be separately created, e.g., by 05-W-internet-cloud-fs.bat in Windows  
#
# Sync-DQ-Cloud; only create directories.  
# They will be populated directly from Sync-DQ-Cloud
# (or in a pinch from offline storage, or partly from github).  
cd ~

mkdir -p 0/Floor  
mkdir -p 0/Sound/1/Wp  
mkdir -p 0/Board/1/Ww

mkdir -p 1/Store  

# eof 05-VMw-sync-dq-cloud-fs
