#!/usr/bin/env bash
# (@) 00-linux-new-setup
# Last-edited: 2022.03.04.1021.Fri -- Danny Quah (me@DannyQuah.com)
# ----------------------------------------------------------------  
# Revision History:
#  % Sun 2018.09.28.0500 - Danny Quah (me@DannyQuah.com)
#    First draft
# ---------------------------------------------------------------- 
install_one() {
# This to install just one, mostly for experimentaiton
  sudo apt -y install \
    curl git
# change the line above as needed
  sudo apt update
# end install_one()
}

## Begin execution here
sudo apt update
sudo apt upgrade -y

## Run function to try out just one thing
# install_one

## If there is time, uncomment the below to install those scripts
## that will take a while
## If needed
source ./00-linux-prelims-install

## This assumes the filesystem has already initialised, following syncthing
# Initialise links
source ./05-linux-links-init

# installBaseApps
source ./11-linux-baseapps-install
# installLevel1Apps
source ./12-linux-level1-apps-install
# installSpecialApps
source ./13-linux-specialapps-install
# install AppImageFiles
source ./15-linux-appimage-install
# installLargeApps
source ./21-linux-largeapps-install
sudo apt-get update
# initialise Desktop
source ./linux-desktop-init
#
# EOF 00-linux-new-setup
#
