#!/usr/bin/env sh
# @(#) 05-linux-links-init // NOT on Windows>VMware
# as ~/0 will connect elsewhere.
# This calls 05-llinks-inside-init; this last can
# be used on Windows>VMware
# Last-edited: 2022.10.01.0819.Sat -- Danny Quah (me@DannyQuah.com)
# ****************************************************************
# Revision History:
#  % 2020.05.25.0620.Mon -- Danny Quah (me@DannyQuah.com)
#    First draft: Initialise with symbolic links to $HOME/
#    This assumes my ~/0 filesystem is already in place
#    Fonts under $DBNF rather than $DBPF as the latter often
#    starts out from github, and I don't want font binaries up
#    there
# ****************************************************************
#
################################
# One-time check on 0/ folders (for path and cleanliness generally)
cd ~
#                              # Other Obsidian vaults' parent folders
mkdir -p 0/Board/1
mkdir -p 0/Sound/1
mkdir -p 0/Props/1/LKYSPP-Deans-Office
#                              # Referents
mkdir -p 0/Floor/1/t
mkdir -p 0/Light/1/j
mkdir -p 0/Light/1/t 
mkdir -p 0/Scene/1
mkdir -p ~/tmp
################################
#

source ./05-llinks-inside-init

################################


# eof 05-linux-links-init
