#!/usr/bin/env bash
# (@) 06-Wiki-Personal-setup
# Last-edited: 2022.02.25.1720.Fri -- Danny Quah (me@DannyQuah.com)
# ----------------------------------------------------------------  
# Revision History:
#  % 2022.02.25.1714.Fri -- Danny Quah (me@DannyQuah.com)
#    First draft. Clone from 01-barebones-new-setup for Wiki-Personal
# ---------------------------------------------------------------- 
cd ~
mkdir -p 0/Sound/1
cd 0/Sound/1
git clone https://github.com/DannyQuah/Wiki-Personal.git Wp

# EOF 06-Wiki-Personal-setup

