#!/usr/bin/env bash
# @(#) 11-linux-baseapps-install
# Last-edited: 2022.02.25.1543.Fri -- Danny Quah (me@DannyQuah.com)
# ----------------------------------------------------------------
# Revision History:
#  % Fri 2018.09.28.0500 -- Danny Quah (me@DannyQuah.com)
# ----------------------------------------------------------------
#
installBaseApps() {
# Base Apps
#  sudo apt --fix-broken install
  sudo apt install -y apt-file \
    bzip2 \
    zip
###############################
# vim/gvim
  sudo apt install -y vim-athena
  # OR instead
  # sudo apt -y install vim-gtk3
###############################
# end installBaseApps()
}

## Begin execution here
sudo apt update
sudo apt upgrade -y

installBaseApps

sudo apt update

#
# EOF 11-linux-baseapps-install
#
