#!/usr/bin/env bash
# @(#) 11-linux-baseapps-install
# Last-edited: 2022.03.02.1900.Wed -- Danny Quah (me@DannyQuah.com)
# ----------------------------------------------------------------
# Revision History:
#  % Fri 2018.09.28.0500 -- Danny Quah (me@DannyQuah.com)
# ----------------------------------------------------------------
#
installBaseApps() {
# Base Apps
#  sudo apt --fix-broken install
  sudo apt install -y apt-file \
    bzip2 \
    doublecmd-gtk \
    zip
###############################
# vim/gvim
sudo apt -y install vim-gtk3
# OR
#  sudo apt install -y vim-athena
# However, vim-athena doesn't show font selector with guifont=*
# or from menubar//Edit
###############################
# not as essential but small and useful
  sudo apt install -y apt-utils \
    gcal
# end installBaseApps()
}

## Begin execution here
sudo apt update
sudo apt upgrade -y

installBaseApps

sudo apt-file update
sudo apt update

#
# EOF 11-linux-baseapps-install
#
