#!/usr/bin/env bash
# @(#) 13-linux-specialapps-install
# Last-edited: 2023.04.05.2112.Wed -- Danny Quah (me@DannyQuah.com)
# ----------------------------------------------------------------
# Revision History:
#  % 2022.02.27.1313.Sun -- Danny Quah (me@DannyQuah.com)
#    apt-key is deprecated and no longer used from Ubuntu 22.04.
#    Its use below is gradually being replaced by -keyring.gpg // Use
#    syncthing as example.
#  % Tue 2018.09.18.1200 -- Danny Quah (me@DannyQuah.com)
#    First draft:
#    Install Linux special apps, those needing special repositories
# ----------------------------------------------------------------
#
installSpecialApps() {
	# Special Apps that need other things (wget, curl, etc.) for
	# their installation. These will be merged into InstallBaseApps()
	# as deb repositories add them
################################
# atom-old-version - doesn't update; updated 2020.05.23.1247h
#  cd ~
#  sudo wget -O atom-amd64.deb "https://atom.io/download/deb"
#  sudo dpkg -i atom-amd64.deb
#  rm -rf atom-amd64.deb
################################
## atom 2020.05
## Add official repository,so apt updates now possible
## https://flight-manual.atom.io/getting-started/sections/installing-atom/##platform-linux
#wget -qO - https://packagecloud.io/AtomEditor/atom/gpgkey | sudo apt-key add -
#sudo sh -c 'echo "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main" > /etc/apt/sources.list.d/atom.list'
#sudo apt update
#sudo apt install -y atom
################################
## firefox
#  cd ~
#  wget -O - "https://download.mozilla.org/?product=firefox-latest&os=linux64&lang=en-US" | sudo tar xJ -C /opt/
#  sudo ln -s /opt/firefox/firefox /usr/local/bin/firefox
################################
## Google Chrome
  cd ~
  wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  sudo dpkg -i google-chrome-stable_current_amd64.deb
  rm -rf google-chrome-stable_current_amd64.deb
################################
# joplin 2019.10.13 1400h
##  wget -O - https://raw.githubusercontent.com/laurent22/joplin/master/Joplin_install_and_update.sh | bash
################################
# mendeley
#  cd ~
#  sudo wget -O mendeley.deb "https://www.mendeley.com/repositories/ubuntu/stable/amd64/mendeleydesktop-latest"
#  sudo dpkg -i mendeley.deb
#  rm -rf mendeley.deb
################################
# panwriter 2021.11
# sudo snap install panwriter
################################
# shotcut video editing
  sudo snap install shotcut --classic
################################
# spotify
  sudo snap install spotify
### Older method below
##  cd ~
# 1. Add the Spotify repository signing keys to be able to verify downloaded packages
##  sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90

# 2. Add the Spotify repository
##  echo deb http://repository.spotify.com stable non-free | sudo tee /etc/apt/sources.list.d/spotify.list

# 3. Update list of available packages
##  sudo apt update

# 4. Install Spotify
##  sudo apt install -y spotify-client
################################
## syncthing
# Add the release PGP keys:
  sudo curl -s -o /usr/share/keyrings/syncthing-archive-keyring.gpg https://syncthing.net/release-key.gpg
# Add the "stable" channel to your APT sources:
  echo "deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable" | sudo tee /etc/apt/sources.list.d/syncthing.list
#
  sudo apt update
  sudo apt install -y syncthing
################################
# onenote 2019.11
#  sudo snap install p3x-onenote
################################
# wechat
#  sudo snap install electronic-wechat
################################
# signal-desktop 2021.01
  sudo snap install signal-desktop
################################
## Telegram // now can use snap instead, so take out
#  cd ~
#  wget -O- https://telegram.org/dl/desktop/linux | sudo tar xJ -C /opt/
#  sudo ln -s /opt/Telegram/Telegram /usr/local/bin/telegram-desktop
# telegram-desktop 2020.02
  sudo snap install telegram-desktop
################################
# termius
#  sudo snap install termius
################################
################################
# typeapp email
#  sudo snap install typeapp-mail 
################################
# typora 2019.05
#  wget -qO - https://typora.io/linux/public-key.asc | sudo apt-key add
# add Typora's repository
#  sudo add-apt-repository 'deb https://typora.io/linux ./'
#  sudo apt update
#  sudo apt install -y typora
# Set the below in linux-links-init
#  mkdir -p ~/.config/Typora/themes
#  cd ~/.config/Typora/themes
#  ln -s ~/0/Scene/1/db0/machines/Editors/Typora.base.user.css ./base.user.css
################################
## youtube-dl
sudo curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl
################################
# zsh 2020.05
# sudo apt install -y zsh
# sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
################################
# zoom 2023.04
################################
sudo apt install -y libgl1-mesa-glx libegl1-mesa libxcb-xtest0 libxcb-cursor0  
## Download zoom_amd64.deb from zoom.us
# sudo dpkg --install zoom_amd64.deb  
# installSpecialApps()
}

# Execution begins here
sudo apt update
sudo apt upgrade -y

installSpecialApps

sudo apt update

# eof 13-linux-specialapps-install
