#!/usr/bin/env sh
# @(#) 30-linux-onedrive-prep
# Last-edited: 2023.03.25.1058.Sat -- Danny Quah (me@DannyQuah.com)
# ----------------------------------------------------------------
# Revision History:
#  % 2023.03.25.1048.Sat -- Danny Quah (me@DannyQuah.com)
#    First draft: sh script to.clean then update OS before 
#    installing onedrive client
# ----------------------------------------------------------------
trap 'exit 0' 2 15 

#  Remove old PPA onedrive (as needed):  
sudo apt remove onedrive
sudo add-apt-repository --remove ppa:yann1ck/onedrive

source ./update-os  

echo Reboot system ...  

# vim: filetype=sh
# eof 30-linux-onedrive-prep

