#!/usr/bin/env zsh
# @(#) $HOME/0/Scene/1/db/machines/Zsh/Zshrc
# Last-edited: Sun 2020.12.06.2043 -- Danny Quah (me@DannyQuah.com)
# ----------------------------------------------------------------
# $
## Revision History:
#  % Sun 2020.10.25.0431 -- Danny Quah (me@DannyQuah.com)
#    unsetopt BG_NICE as my WSL on kve2.dq-w10 generates an 
#    error on each directory change otherwise
#  % Sun 2020.10.18.0054 -- Danny Quah (me@DannyQuah.com)
#    ZSH_DISABLE_COMPFIX true for W10 / WSL
#  % Sun 2020.07.19.1458 -- Danny Quah (me@DannyQuah.com)
#    Added into Bash-dispatcher git use functions
#    that were previously in Common/Shellsrc;
#    zsh needs to run git plugin for those and others as certain
#    themes such as gallois need a lot of git plugin
#  % Sun 2020.05.24.1915 -- Danny Quah (me@DannyQuah.com)
#    git plugin is overkill for now, so take it out
#  % Sat 2020.05.23.1657 -- Danny Quah (me@DannyQuah.com)
#    First draft. From ~/.oh-my-zsh/templates/zshrc.zsh-template
#    Upgrade Oh My Zsh is upgrade_oh_my_zsh
# ----------------------------------------------------------------
# Following https://github.com/rupa/z/pull/200
unsetopt BG_NICE
#
ZSH_DISABLE_COMPFIX="true"
# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
# Allowed in https://github.com/ohmyzsh/ohmyzsh and recommended
# https://opensource.com/article/19/9/adding-plugins-zsh following
# Free Desktop http://freedesktop.org/ specification
# export ZSH="/home/dq/.oh-my-zsh"
export ZSH="$HOME/.local/share/oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
# ZSH_THEME="robbyrussell"
ZSH_THEME=random

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# (DQ) See which gets chosen in $RANDOM_THEME
# ZSH_THEME_RANDOM_CANDIDATES=(
#  "robbyrussell"
#  "pygmalion"
#  "agnoster"
#  "linuxonly"
#  "risto"
#  "theunraveler"
#  )

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
# I took out (ubuntu), replaced key items in Shellsrc:
# This saves time and lets me use those aliases in bash as well.
# But, e.g., gallois zsh theme needs a lot more of git, so now
# I've put that back in, and adjusted Shellsrc
plugins=(git vi-mode z)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

#
# All below adjustments by DQ
# Shorten prompt
# https://unix.stackexchange.com/questions/273529/shorten-path-in-zsh-prompt
# export PROMPT='%(5~|…/%3~|%~)'

source ${HOME}/0/Scene/1/db/machines/Common/Shellsrc

# Noticed these are here from somewhere and I'd prefer not to have them
unalias md rd

# Normal aliases in Shellsrc

# Suffix aliases
alias -s md=typora
alias -s txt=vim

# Global aliases
# alias -g L="| less"
# alias -g G="| grep"

# Autoloads
autoload -U zmv
# batch rename, e.g., zmv -Wv "TimePhoto_20201*" "2020.1*"

# Parameterised aliases
function Largest() {
	find -L $1 -type f -printf "%s %p\n" | sort -nr | head $2
}

function acs() {
  apt-cache search $1 | grep $2
}

# eof Zshrc

