#!/usr/bin/env bash
# @(#) $HOMESCENE/1/db0/machines/Bash/Bash-Windows -> .bashrc
# Last-edited: Wed 2022.01.12.2329 -- Danny Quah (me@DannyQuah.com)
# ----------------------------------------------------------------
# Revision History:
#  % Tue 2013.01.29.1220 -- Danny Quah (dquah@LSE016404)
#    First draft
# ----------------------------------------------------------------
#
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

if [ -f ${HOME}/1/db0/machines/Bash/Bash-dispatcher ]; then
  source ${HOME}/1/db0/machines/Bash/Bash-dispatcher
elif [ -f ~/.bash-dispatcher ]; then
  source ~/.bash-dispatcher
fi

# Local Variables:
# end:
# eof Bash-Windows
