#!/bin/bash
# @(#) toggle-touchpad
# Last edited: 2020.05.07 1800h -- Danny Quah
#

TOGGLE=$HOME/.toggle-touchpad
TOUCHPAD_ID=$(xinput list | grep "Touchpad" | grep -Eow '[0-9]{2}')

if [ ! -e $TOGGLE ]; then
   touch $TOGGLE
   xinput set-prop $TOUCHPAD_ID "Device Enabled" 0
else
   rm $TOGGLE
   xinput set-prop $TOUCHPAD_ID "Device Enabled" 1
fi
