#!/usr/bin/env bash
# @(#) $HOME/0/Scene/1/db0/machines/Common/Shellsrc
# Last-edited: 2023.04.03.0534.Mon -- Danny Quah (me@DannyQuah.com)
# ----------------------------------------------------------------
# Revision History:
#  % Sat 2021.12.11.1706 -- Danny Quah (me@DannyQuah.com)
#    VimWiki -> Wp, Ww
#  % Sun 2020.07.19.1458 -- Danny Quah (me@DannyQuah.com)
#    Added into Bash-dispatcher git use functions
#    that were previously in Common/Shellsrc;
#    zsh needs to run git plugin for those and others as certain
#    themes such as gallois need a lot of git plugin
# Have decided to leave ATOM_HOME at its default, so each machine
# keeps something its own. Otherwise, the cloud server/syncthing on
# Scene keeps having to move lots of atom customisation about, needlessly,
# as a lot of what gets put there is just one-time from the atom.io/
# anyway
#  % Mon 2020.05.25.1142 -- Danny Quah (me@DannyQuah.com)
#    First draft: Commands in common across .bashrc and .zshrc
# ----------------------------------------------------------------

#
# Still need a way to separate when coming in on ssh, whereupon xmodmap
# not needed anywhere.
#
# Branch on machine ----------------------------------------------
case "$HOSTNAME" in
	ltppu15*)
# VMware but don't see yet a better way to test for it
# Might move to /etc/fstab but then there won't be an obvious record
		# used to have 00-VMw-connect-fs-hack contents here but
		# replaced with /etc/fstab entry
		# if [ ! -d ~/0/Light ]; then
			# ~/00-VMw-connect-fs-hack
			# no-op
		# fi
		;;
	ttd*)
		;;
	xbook*)
		;;
	iPad-Pro*)
		;;
	PC1MDCKR*)
# WIN_DIRS for Ubuntu use under WSL; not needed on real Ubuntu machines
    WIN_DIRS="/mnt/c/Users/sppdqlsh /mnt/d/dq"
		;;
esac

# Branch on OS ---------------------------------------------------
case "$OSTYPE" in
  linux*)
    BIN_DIRS="${HOME}/local/bin ${HOME}/bin"
#    MANPATH=$MANPATH:"/usr/local/texlive/2022/texmf-dist/doc/man"
#    INFOPATH=$INFOPATH:"/usr/local/texlive/2022/texmf-dist/doc/info"
    DC_CONFIG_PATH="${HOME}/0/Scene/1/db0/Config/DoubleCmd-Linux"

# Keyboard -------------------------------------------------------
## setxkbmap -option "ctrl:nocaps"
    if [[ -s ~/.Xmodmap && -n "${DISPLAY+x}" ]]; then
     xmodmap ~/.Xmodmap
    fi
#  if [ -s ~/.Xmodmap-swapctrlcaps ]; then
#    xmodmap ~/.Xmodmap-swapctrlcaps
#  fi
#
#  alias xbook-biscroff='xrandr --output eDP-1 --off'
  ;;
  msys*)
# Shell and GNU utilities, part of MinGW
    BIN_DIRS="${HOME}/bin ${HOME}/local/bin /c/ProgramData/chocolatey/bin /c/texlive/2020/bin/win32" 
     ;;
  *)
# Catch-all everything else
#  export ATOM_HOME=~/0/Scene/1/db/machines/Editors/Atom.w
    # do nothing, accept defaults
    #   export ATOM_HOME="~/.atom"
    ;;
esac


# ###############################
# Settings
umask 022 
set -o noclobber

# ###############################
# Formats and languages
# export LC_LOCALE=en_SG.utf-8
# On Linux machines, sort otherwise ignores "." so that
# "Li.H" and "Li.X" would then be separated by "Lin.A". No harm
# putting this in for W10 machines too, so...
# Sat 2022.01.08.0709 -- Danny Quah (me@DannyQuah.com)
# export LANG=C
# mosh requires UTF-8 native locale
export LANG=en_SG.utf-8
# ###############################
#
# Following https://askubuntu.com/questions/432217/prevent-duplicate-entries-in-path  
#
for bindir in $( echo "$BIN_DIRS" ) ; do
  if [ -d "${bindir}" ]; then
    [[ ":${PATH}:" =~ ":${bindir}:" ]] || PATH="${bindir}:${PATH}"
#   PATH="$bindir":$PATH
  fi
done
export PATH=$PATH

#
# ###############################
# Filesystems organisation
TMPDIR=${HOME}/tmp
FSROOT=${HOME}/0
CDPATH=\
${FSROOT}/Wrk/1/:\
${FSROOT}/Scene/1/db0:\
${FSROOT}/OneDrive/1/Wp:\
${FSROOT}/Wrk/1/LKYSPP-Deans-Office:\
${FSROOT}/Wrk/1/People-Gr-Conf:\
${FSROOT}/Wrk/1/j:\
${FSROOT}/Stage/Photos:

for windir in $( echo "$WIN_DIRS" ) ; do
  if [ -d "$windir" ]; then
    CDPATH=$CDPATH:"$windir"
  fi
done
export CDPATH=$CDPATH
# source /usr/share/autojump/autojump.sh

#
# ###############################
# Email management - I sync Gmail for
# offline use
alias olm="offlineimap"
alias olq="offlineimap -q"
#
#
# ###############################
# https://gnunn1.github.io/tilix-web/manual/vteconfig/
if [ $TILIX_ID ] || [ $VTE_VERSION ]; then
	if [ -f /etc/profile.d/vte.sh ]; then
	  source /etc/profile.d/vte.sh
#	elif [ -f /etc/profile.d/vte.csh ]; then
#		source /etc/profile.d/vte.csh
	fi
fi

# ###############################
# GNOME Terminal management
# https://makandracards.com/makandra/494001-linux-how-to-make-a-terminal-window-title-reflect-the-current-path
# ###############################
set-window-title() {
  echo -en "\033]0;$(pwd | sed -e "s;^$HOME;~;")\a"
}

if [[ "$PROMPT_COMMAND" ]]; then
  export PROMPT_COMMAND="$PROMPT_COMMAND;set-window-title"
else
  export PROMPT_COMMAND=set-window-title
fi
# ###############################
# tmux is now my terminal multiplexer
# if [ -d "/tmp/tmux-1000" ]; then
#   set ...
# fi

# on Toshiba-ttd-Tecra-Dynabook-2023.03 
alias tmntt="tmux -u new-session -s ttd"
alias tmatt="tmux -u attach -t ttd"
# ... ttd mosh/ssh-logged into xbook
alias tmnxttd="tmux -u new-session -s xttd"
alias tmaxttd="tmux -u attach -t xttd"

# on Dell-xbook-XPS-13-9350-2016.03  
alias tmnx="tmux -u new-session -s xb"
alias tmax="tmux -u attach -t xb"  

# on Apple-iPad-Pro-5G-12.9-2022.08 over mosh or similar  
alias tmnxi5="tmux -u new-session -s xbook-ip5"
alias tmaxi5="tmux -u attach -t xbook-ip5"

# on Apple-iPad-Pro-5G-12.9-2022.08 // iSH  
alias tmni5="tmux -u new-session -s i5"
alias tmai5="tmux -u attach -t i5"

# on Lenovo-ltpp15-Thinkpad-P15s-2022.04 // ltpp15u  
alias tmnlt="tmux -u new-session -s lt"
alias tmalt="tmux -u attach -t lt"
alias tmntlt="tmux -u new-session -s ttd-lt"
alias tmatlt="tmux -u attach -t ttd-lt"
alias tmnxlt="tmux -u new-session -s xbook-lt"
alias tmaxlt="tmux -u attach -t xbook-lt"
#

#
# ###############################
# Since 2021.08 update to "Backup and Sync",
# Google Drive now defaults to no "w" permission
# on folders in my setup.  So, reassert "w"
# but also more generally to the sensible "755".
# (Sat 2021.10.02.0830)
case "$OSTYPE" in
  linux*)
    if [ -d "~/0/Floor" ]; then
      find -L ~/0/Floor -type d -exec chmod 755 {} \;
    fi
    ;;
  *)
    # do nothing for now on others
    ;;
esac

# ###############################
#
# Timezone
export TZ='Asia/Singapore'
# export TZ='Europe/London'
# export TZ='America/New_York'

# ###############################
# What zsh calls normal aliases, and bash just aliases

alias python='/usr/bin/python3'
# apt use - took out ubuntu plugin
APT=apt
# APT=apt-get
# alias afs='apt-file search --regexp'
# alias agi='sudo $APT install'
# alias agp='sudo $APT purge'
# alias agr='sudo $APT remove'
# alias agu='sudo $APT update'
alias agud='sudo $APT update && sudo $APT dist-upgrade'
# alias agug='sudo $APT upgrade'
# alias aguu='sudo $APT update && sudo $APT upgrade'

alias dbi='sudo dpkg --install'

alias ls='/bin/ls' # since many systems set this elsewhere to '/bin/ls --color=auto'
alias ll='/bin/ls -lF'
alias lt='/bin/ls -ltF'
alias lf='/bin/ls -F'
alias la='ls -A'
# alias l='ls -CF'

# largest files recursively from here
# alias Largest='find -L . -type f -printf "%s %p\n" | sort -nr | head -20'

alias trash='zip -m9or ${TMPDIR}/dq-trash $@'
# alias notabs-dq='sed -ie "s/\t//g" $@'
alias tabscomma='sed "s/\t/,/g" $@'
# find files containing text from this directory
alias greptextf='grep --exclude-dir={.git} -rnw . -e $@'
# clean find from root avoiding directories that aren't relevant
alias cleanrootfind='find / -type d \( -name "proc" -o -name "var" -o -name "run" -o -name "dev" -o -name "tmp" \) -prune -o'
# filepath lengths longer than 249 chars plus /home/dq if running there
# https://unix.stackexchange.com/questions/61197/command-to-find-file-path-lengths-that-are-too-long-for-burning-to-dvd  
alias find-longfn='find ./ -regextype posix-extended -regex '.{249,}''
# grep md files recursively from current directory
alias grepmd='find -L . -type d ! -readable -prune -o -type f -name "*.md" ! -path "*/Trash/*" -print0 | xargs -0 grep $@ '
# grep Deans-Office wiki recursively
alias grepwd='grep --include=\*.md --colour=never -rnw ~/0/Wrk/1/LKYSPP-Deans-Office/Wd -e $@'
# grep personal wiki recursively
alias grepwp='grep --include=\*.md --colour=never -rnw ~/0/Sound/1/Wp -e $@'
# grep work wiki recursively
alias grepww='grep --include=\*.md --colour=never -rnw ~/0/Board/1/Ww -e $@'
# alias grep1n='find -L ~/0/Board/1/1-Notes -type f -name "*.md" -exec grep -EH $@ {} ";"'
# alias dollmd-dq="sed -ie 's/ \$/ \\$/g' $@"
# alias starmd-dq="sed -ie 's/ \*/ \\*/g' $@"

alias synclog='grep $@ /var/log/syslog'
#  for onedrive, syncthing

alias syncconf-find='find -L ~/0 -type f -name "*sync-conflict*"'
alias syncconf-trash='find -L ~/0 -type f -name "*sync-conflict*" | zip -m9@ ${TMPDIR}/dq-trash'
alias texcln='zip -m9o ${TMPDIR}/dq-trash *.blg *.log *.aux *.nav *.out *.snm *.synctex.gz *.toc *.tex~'

#---------------------------------------------------------------------# 
# Below just archive; all commented out ------------------------------
#---------------------------------------------------------------------# 
# Aliases for scaling on Pixelbook - also through .desktop in
# ~/.local/share/applications/
# alias atomqpb="atom --force-device-scale-factor=1.8"
# alias extterm="sommelier -X -scale0.6 -dpi=140 /usr/bin/extraterm"
# alias tbqpb="sommelier -X --scale=0.6 --dpi=140 /usr/bin/thunderbird"
# alias loqpb="sommelier -X --scale=0.6 --dpi=120 /usr/bin/libreoffice6.1"
# alias fotext="sommelier -X --scale=0.6 --dpi=140 /usr/bin/textmaker18free"
# alias foplan="sommelier -X --scale=0.6 --dpi=140 /usr/bin/planmaker18free"
# alias fopres="sommelier -X --scale=0.6 --dpi=140 /usr/bin/presentations18free"

# But I prefer not to have colors --- too distracting
# askubuntu.com/questions/466198/how-do-i-change-the-color-for-directories-with-ls-in-the-console
# LS_COLORS=$LS_COLORS:'di=0;35:' ; export LS_COLORS

## Filesystems pre-2019.05
# export GGDDIR=${HOME}/0/Floor # Google Docs will only save to Google Drive
# export DRPDIR=${HOME}/0/Scene/1 # Legacy Dropbox, but no gain from Google Drive
# export BRDDIR=${HOME}/0/Board #
# export SCNDIR=${HOME}/0/Scene
# export STGDIR=${HOME}/0/Stage #
# export CDPATH=${GGDDIR}/1/t:${BRDDIR}/1/1-Notes:${BRDDIR}/1/t:${SCNDIR}/1/t/Writings/Notes-Events:${GGDDIR}/1/t/Writings:${GGDDIR}/1/j:${DRPDIR}/db:${DRPDIR}/i:${STGDIR}/Photos:

# Tue Jan 21 13:26:16 2014 - Danny Quah (dquah@spartan)
# With texlive 2012 on, there is no longer need for all this.  Just
# put everything in ~/texmf/
# TEXINPUTS discouraged
# TeX (extra colon allows texmf.cnf [or compiled default]
# export TEXINPUTS=.:$SHAREDIR/t/dbs/tex/:$LOCALDIR/db/machines/[Linux,Windows]:
# TEXINPUTS has a Linux/Windows dependency and so is set in Bash-Linux
# or Bash-Windows instead
# export BSTINPUTS=.:$GGDDIR/t/dbs/tex:
# export BIBINPUTS=.:$GGDDIR/t/dbs/tex:

# alias mountfloor='google-drive-ocamlfuse ${HOMEFLOOR}'
# alias umountfloor='fusermount -u ${HOMEFLOOR}'

# alias dvitmp='/usr/bin/dvips -Ppdf -D600 $@ -o ~/tmp/0.ps'
# alias econbash='ssh -i ~/.ssh/id_rsa dquah@econ.lse.ac.uk "/bin/bash --login"'

# LSE vpn needs to be connected for this mount
# alias lsepwp-mount='sudo mount.cifs //pwp.lse.ac.uk/webs/dquah ${HOME}/Documents/mnt/lsepwp -o user=dquah,domain=lse,uid=dquah'
# alias lsepwp-umount='sudo umount -t cifs $HOME/Documents/mnt/lsepwp'
# DannyQuah.com/www/ - Still trying on this

# Have never quite gotten the below to work but would still like to, one day
# alias mydom-mount='sudo mount -t davfs p3plcpnl0680.prod.phx3.secureserver.net:2078/ ~/Documents/mnt/mydomain'
# Back up my entire blogsite
# Mon Jan 19 15:41:44 2015 - Danny Quah (dquah@spartan)
# http://darcynorman.net/2011/12/24/archiving-a-wordpress-website-with-wget/
# http://www.leancrew.com/all-this/2013/01/local-archive-of-wordpress-posts/

# This below is yet the most hopeful but it's still not working
# alias backup-DQ='wget --mirror -p --html-extension --convert-links -e robots=off -P . http://www.DannyQuah.com/writings/'

# vim: filetype=bash
# eof Shellsrc
