#!/usr/bin/env sh
# @(#) 00-VMw-connect-fs-hack
# Last-edited: 2022.11.11.1655.Fri -- Danny Quah (me@DannyQuah.com)
# Ugly hack to connect up VMware > filesystem until I found
# a better bootstrap.  Now using lines in /etc/fstab as instructed by
# https://kb.vmware.com/s/article/60262  
# However, this works fine to ad hoc mount single filesystems, so...
# ****************************************************************
# Revision History:
#  % 2022.04.24.1914.Sun -- Danny Quah (me@DannyQuah.com) 
# https://docs.vmware.com/en/VMware-Workstation-Pro/16.0/com.vmware.ws.using.doc/GUID-AB5C80FE-9B8A-4899-8186-3DB8201B1758.html
# ****************************************************************
MYGID=`id -g`
MYUID=`id -u`
/usr/bin/vmhgfs-fuse .host:/0 ~/0 -o subtype=vmhgfs-fuse,allow_other,gid=$MYGID,uid=$MYUID
/usr/bin/vmhgfs-fuse .host:/1 ~/1 -o subtype=vmhgfs-fuse,allow_other,gid=$MYGID,uid=$MYUID
################################
# eof 00-VMw-connect-fs-hack
